{%set name = "requests-oauthlib" %}
{%set version = "0.7.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "198807c592b75438485c890f0403b1a8e363c86be1a87da687be18991a6850b0" %}
{%set build_num = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - oauthlib >=0.6.2
    - requests >=2.0.0

  run:
    - python
    - oauthlib >=0.6.2
    - requests >=2.0.0

test:
  imports:
    - requests_oauthlib
    - requests_oauthlib.compliance_fixes

about:
  home: https://github.com/requests/requests-oauthlib
  license: ISC
  license_file: LICENSE
  summary: 'OAuthlib authentication support for Requests.'
  dev_url: https://github.com/requests/requests-oauthlib
  doc_url: https://github.com/requests/requests-oauthlib

extra:
  recipe-maintainers:
    - pmlandwehr
