travis:
  secure:
    BINSTAR_TOKEN: Rlrn/kgjd9h4zvJFinqB4YFK1nkpNIAQJU3W2jGyU4QZKaO2tWpQcptA/XLWf1OS0gsl3r4VA8nHpfKZ8s5J3/YD9Bx68GaR2qDlLLNGxJCHWzPq2XsM8GmCcb0kAt0d9BQMpFrx/VBhxcDrPXfL5MwlE2HpfKsKY5hEI+3Z7tGZUa5FVz6oLCp8jbaAd9dGrF8Cxyugapt8Enhb8ailbFxv1lpPN3uNVT9T4qv0yXAk687qnngsv8k4G77dB5ZLoMKTA8uYu2VHfBDY6FdkyODfWHv6dWeCWU6CTNiX2SaxVgDUQs3LcmfY5AwkF6YMIxUglqQRtoHmBwmk25tdNXPPPwTPV0O18e8/11ZHEQOfjzDY5PJ3xWQkKOdhiJ3XWNWOOD5kWjPSf/u8mKWQQpLiukE6uaCXA5/dRqYNs9gGL0rdaf3Lw489py/9qNrsnBtHgbN5QsDXBaffTfjbPOLzXGiWyVAW4AiJMNkygJWQHTf7mUHV/J5HAeP0oFvciWeBnCFPwChZRIiOmMJGgTbfA8Di+VGo72CgMCbLeL22YguAwE44vcAZ2W0gJK8Ec8V/NTE/aCX1ElQkxZC0JxG5PMRp1OWEUuwkJLf9g/f4801B2ERB0bZxCHVOmKAViunaQOY6eku04M9kaOaTgUvZaCD35e8XCTl7C+ofLtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
