travis:
  secure:
    BINSTAR_TOKEN: ciMzOy9K5FI17+HxqqozftE2Scl8u+7+jaihrIBeBzEKCCsJnu0S99rUK+Eoqh4P2IpIZL9rQ0WBrd+zu6C8azRtRKBx2dzgADc0TdJgeOdd+yinmkLDMFlFxT/5kWRAiAbY+ow0DguVzFL2h3Qt3HXXmfZ7a42a3nY6qDOHVDGf8bzqxPSL4ybbK4DdLBIrZOiPK79yWw1sPg3fDqovX3m76txoXrGcD9bzyD4nnLEpTJ+25r+y5M1Fv4P+aAh+d6sbM6VwrLrKuzeSt/2rRRQoGE2uIkcTf+xHqbw8j/Czy4R57cYJkA7xv44lupmV72gEiSg7fff6c//I4b1cwL09boBorHAiFNWdWKmZ/LPZswO3f8Oh29BEbCP9YAwjl6FZ0JqfbIbgVU2LMfSyjxno85B/o67uiPQpu7Bjy+e1riOXspKDHznJI8CagvqTVNiSHsIeMIU5fotD2wq4W2DrFESBO3F0YjpedVt+/h1whG3bHW/NxJr/tSBFa4mqYFAiCMLEm1dne1Eek+HVDgtvGAaveW1c2UVHRK4ceDryjySxkF/zfwS+tWcYoy1YU4nDCjiTnLXBr5Jis5gGulbSj1ABHWg5ONac8goX7Su7vdGbIJftBC8TWnJTe8Sy0j3tmg1wtW9HOPhHvJvkt3IFVyaGKph1UE4doOLGbyo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
